#!/bin/bash
outdir=$1
time=$2

echo downloading $2 seconds of video to $1

prefix=$(date '+%Y%m%d%H%M')

mkdir -p $outdir/$prefix

for i in $(seq 1 $time)
do
	out=$(date '+%Y%m%d%H%M%S.jpg')
	./snapshot > $outdir/$prefix/$out &
	echo Dl $i
	sleep 1
done

cat $outdir/$prefix/*.jpg | ffmpeg -r 1 -i - -pix_fmt yuv420p -r 10 $outdir/$prefix/video.mkv
