FROM alpine:3.6
MAINTAINER niles.c@gmail.com

RUN apk update

RUN apk fetch openjdk8
RUN apk add openjdk8

RUN mkdir -p /opt/downloader

COPY Downloader.java /opt/downloader
WORKDIR /opt/downloader
ENV JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk
ENV PATH="$JAVA_HOME/bin:${PATH}"

RUN javac Downloader.java

CMD ["java", "Downloader"]
